name: test-environment
channels:
  - esri
  - conda-forge
  - fastai
  - pytorch

dependencies:
  - python=3.7
  - somoclu
  - fiona
  - scikit-learn
  - numpy
  - pandas >=1
  - pip
  - matplotlib
  - seaborn
  - arcgis
  - scipy
  - pillow
  - numpy
